apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineDeployment
metadata:
  name: standard-workers
  namespace: ${namespace}
spec:
  #paused: true [uncommment this when you want to pause]
  #rollbackTo:
    #revision: 0 [uncommment this when you want to rollback to previous version]
  replicas: ${worker_count}
  minReadySeconds: 500 # Minimum time to wait for machine to be ready
  strategy: 
    type: RollingUpdate # Strategy for update RollingUpdate/Recreate
    rollingUpdate:
      maxSurge: 1 # Maximum addition machines that spawned over the desired replicas during update
      maxUnavailable: 1 # Maximum unavailable machines that the cluster can tolerate
  selector:
    matchLabels:
      node-type: standard-worker # Label to match the template (XXXXX)
  template:
    metadata:
      labels:
        node-type: standard-worker # Label to match with selector (XXXXX)
    spec: 
      class:
        kind: OpenStackMachineClass # Machine class template used to create machine, could be AWS/GCP/Azure/Other-cloud-providers
        name: standard-worker # Name of the machine class

