apiVersion: v1
kind: Secret
metadata:
  name: worker-nodes
  namespace: ${namespace}
type: Opaque
data:
  userData:   "${cloud_init_b64}"
  authURL:    "${auth_url_b64}"
  username:   "${username_b64}"
  password:   "${password_b64}"
  ${domain_key}: "${domain_value_b64}"
  ${tenant_key}: "${tenant_value_b64}"
  insecure:   "${insecure_b64}"
  caCert:     "${cacert_b64}"

