apiVersion: v1
kind: Secret
metadata:
  name: worker-nodes
  namespace: ${namespace}
type: Opaque
data:
  userData:   "${cloud_init_b64}"
  providerAccessKeyId: "${access_key_b64}"
  providerSecretAccessKey: "${secret_key_b64}"
